In [86]:

import pandas as pd

creating a dataframe

In [91]:
import pandas as pd

data = {
    'Nmae': ['alice','bob', 'charlie'],
    'Age': [25, 30, 35],
    'City': ['New York' , 'Los Angels' , 'Chicago']
} # removed extra indent on this line
df = pd.DataFrame(data)
print(df)

      Nmae  Age        City
0    alice   25    New York
1      bob   30  Los Angels
2  charlie   35     Chicago

Reading data from a CSV File

In [93]:
df = pd.read_csv('/content/Pokemon (1).csv')

In [94]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [95]:
print(df.tail())

       #                 Name   Type 1 Type 2  Total  HP  Attack  Defense  \
795  719              Diancie     Rock  Fairy    600  50     100      150
796  719  DiancieMega Diancie     Rock  Fairy    700  50     160      110
797  720  HoopaHoopa Confined  Psychic  Ghost    600  80     110       60
798  720   HoopaHoopa Unbound  Psychic   Dark    680  80     160       60
799  721            Volcanion     Fire  Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [97]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [98]:
print(df.isnull().sum())

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [99]:
print(df.dtypes)

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

DATA selection and filtering

In [100]:
print(df['Name'])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [102]:
print(df[['Name','Type 1','Total']])

                      Name   Type 1  Total
0                Bulbasaur    Grass    318
1                  Ivysaur    Grass    405
2                 Venusaur    Grass    525
3    VenusaurMega Venusaur    Grass    625
4               Charmander     Fire    309
..                     ...      ...    ...
795                Diancie     Rock    600
796    DiancieMega Diancie     Rock    700
797    HoopaHoopa Confined  Psychic    600
798     HoopaHoopa Unbound  Psychic    680
799              Volcanion     Fire    600

[800 rows x 3 columns]

In [103]:
print(df.iloc[0])
print(df.iloc[:5])

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
Total               318
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object
   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4  4             Charmander   Fire     NaN    309  39      52       43

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False

In [104]:
fire_pokemon = df.loc[df['Type 1'] == 'Fire']
print(fire_pokemon)

       #                       Name Type 1    Type 2  Total   HP  Attack  \
4      4                 Charmander   Fire       NaN    309   39      52
5      5                 Charmeleon   Fire       NaN    405   58      64
6      6                  Charizard   Fire    Flying    534   78      84
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104
42    37                     Vulpix   Fire       NaN    299   38      41
43    38                  Ninetales   Fire       NaN    505   73      76
63    58                  Growlithe   Fire       NaN    350   55      70
64    59                   Arcanine   Fire       NaN    555   90     110
83    77                     Ponyta   Fire       NaN    410   50      85
84    78                   Rapidash   Fire       NaN    500   65     100
135  126                     Magmar   Fire       NaN    495   65      95
147  136                    Flareon   Fire       NaN    525   65     130
158  146                    Moltres   Fire    Flying    580   90     100
169  155                  Cyndaquil   Fire       NaN    309   39      52
170  156                    Quilava   Fire       NaN    405   58      64
171  157                 Typhlosion   Fire       NaN    534   78      84
236  218                     Slugma   Fire       NaN    250   40      40
237  219                   Magcargo   Fire      Rock    410   50      50
259  240                      Magby   Fire       NaN    365   45      75
263  244                      Entei   Fire       NaN    580  115     115
270  250                      Ho-oh   Fire    Flying    680  106     130
276  255                    Torchic   Fire       NaN    310   45      60
277  256                  Combusken   Fire  Fighting    405   60      85
278  257                   Blaziken   Fire  Fighting    530   80     120
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160
352  322                      Numel   Fire    Ground    305   60      60
353  323                   Camerupt   Fire    Ground    460   70     100
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120
355  324                    Torkoal   Fire       NaN    470   70      85
435  390                   Chimchar   Fire       NaN    309   44      58
436  391                   Monferno   Fire  Fighting    405   64      78
437  392                  Infernape   Fire  Fighting    534   76     104
518  467                  Magmortar   Fire       NaN    540   75      95
542  485                    Heatran   Fire     Steel    600   91      90
557  498                      Tepig   Fire       NaN    308   65      63
558  499                    Pignite   Fire  Fighting    418   90      93
559  500                     Emboar   Fire  Fighting    528  110     123
572  513                    Pansear   Fire       NaN    316   50      53
573  514                   Simisear   Fire       NaN    498   75      98
614  554                   Darumaka   Fire       NaN    315   70      90
615  555    DarmanitanStandard Mode   Fire       NaN    480  105     140
616  555         DarmanitanZen Mode   Fire   Psychic    540  105      30
692  631                    Heatmor   Fire       NaN    484   85      97
721  653                   Fennekin   Fire       NaN    307   40      45
722  654                    Braixen   Fire       NaN    409   59      59
723  655                    Delphox   Fire   Psychic    534   75      69
730  662                Fletchinder   Fire    Flying    382   62      73
731  663                 Talonflame   Fire    Flying    499   78      81
735  667                     Litleo   Fire    Normal    369   62      50
736  668                     Pyroar   Fire    Normal    507   86      68
799  721                  Volcanion   Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         43       60       50     65           1      False
5         58       80       65     80           1      False
6         78      109       85    100           1      False
7        111      130       85    100           1      False
8         78      159      115    100           1      False
42        40       50       65     65           1      False
43        75       81      100    100           1      False
63        45       70       50     60           1      False
64        80      100       80     95           1      False
83        55       65       65     90           1      False
84        70       80       80    105           1      False
135       57      100       85     93           1      False
147       60       95      110     65           1      False
158       90      125       85     90           1       True
169       43       60       50     65           2      False
170       58       80       65     80           2      False
171       78      109       85    100           2      False
236       40       70       40     20           2      False
237      120       80       80     30           2      False
259       37       70       55     83           2      False
263       85       90       75    100           2       True
270       90      110      154     90           2       True
276       40       70       50     45           3      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
352       40       65       45     35           3      False
353       70      105       75     40           3      False
354      100      145      105     20           3      False
355      140       85       70     20           3      False
435       44       58       44     61           4      False
436       52       78       52     81           4      False
437       71      104       71    108           4      False
518       67      125       95     83           4      False
542      106      130      106     77           4       True
557       45       45       45     45           5      False
558       55       70       55     55           5      False
559       65      100       65     65           5      False
572       48       53       48     64           5      False
573       63       98       63    101           5      False
614       45       15       45     50           5      False
615       55       30       55     95           5      False
616      105      140      105     55           5      False
692       66      105       66     65           5      False
721       40       62       60     60           6      False
722       58       90       70     73           6      False
723       72      114      100    104           6      False
730       55       56       52     84           6      False
731       71       74       69    126           6      False
735       58       73       54     72           6      False
736       72      109       66    106           6      False
799      120      130       90     70           6       True

In [107]:
print(df.loc[0, 'Name'])
print(df.loc[0:4, ['Name','Attack']])

Bulbasaur
                    Name  Attack
0              Bulbasaur      49
1                Ivysaur      62
2               Venusaur      82
3  VenusaurMega Venusaur     100
4             Charmander      52